using Microsoft.VisualBasic;
using Microsoft.VisualBasic.Compatibility;
using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
namespace COP2001
{
	[Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]
	partial class OldfrmIndicatorEdit
	{
		#region "Windows Form Designer generated code "
		[System.Diagnostics.DebuggerNonUserCode()]
		public OldfrmIndicatorEdit() : base()
		{
			Load += frmIndicatorEdit_Load;
			//This call is required by the Windows Form Designer.
			InitializeComponent();
		}
//Form overrides dispose to clean up the component list.
		[System.Diagnostics.DebuggerNonUserCode()]
		protected override void Dispose(bool Disposing)
		{
			if (Disposing) {
				if ((components != null)) {
					components.Dispose();
				}
			}
			base.Dispose(Disposing);
		}
//Required by the Windows Form Designer
		private System.ComponentModel.IContainer components;
		public System.Windows.Forms.ToolTip ToolTip1;
		public System.Windows.Forms.CheckBox chkAppCare;
		public System.Windows.Forms.ListBox lstICD;
		public System.Windows.Forms.GroupBox Frame2;
		public System.Windows.Forms.ComboBox cboPatientType;
		public System.Windows.Forms.ListBox lstTotalCases;
		public System.Windows.Forms.ComboBox cboCMSSampleField;
		public System.Windows.Forms.ComboBox cboMeasureDataUsage;
		public System.Windows.Forms.ComboBox cboBaseType;
		public System.Windows.Forms.TextBox txtCMSCode;
		public System.Windows.Forms.TextBox txtJCCode;
		public System.Windows.Forms.ComboBox cboRiskAdjustSGID;
		public System.Windows.Forms.ComboBox cboContinuousSGID;
		public System.Windows.Forms.ComboBox cboEndDateTime;
		public System.Windows.Forms.ComboBox cboStartDateTime;
		public System.Windows.Forms.ComboBox cboStartDateDDID;
		public System.Windows.Forms.ComboBox cboEndDateDDID;
		public System.Windows.Forms.ComboBox cboStartTimeDDID;
		public System.Windows.Forms.ComboBox cboEndTimeDDID;
		public System.Windows.Forms.Label Label25;
		public System.Windows.Forms.Label Label24;
		public System.Windows.Forms.Label Label15;
		public System.Windows.Forms.Label txtStartTime;
		public System.Windows.Forms.Label Label13;
		public System.Windows.Forms.Label Label12;
		public System.Windows.Forms.GroupBox Frame1;
		public System.Windows.Forms.ComboBox cboSPageOrientation;
		public System.Windows.Forms.TextBox txtScale;
		public System.Windows.Forms.ComboBox cboBreakoutType;
		public System.Windows.Forms.ComboBox cboBestPractice;
		public System.Windows.Forms.ComboBox cboMeasureTimeUnit;
		public System.Windows.Forms.ComboBox cboRiskAdjusted;
		public System.Windows.Forms.ComboBox cboCalcType;
		public System.Windows.Forms.ComboBox cboIndicatorType;
		public System.Windows.Forms.TextBox txtJCAHOID;
		private System.Windows.Forms.Button withEventsField_cmdCancel;
		public System.Windows.Forms.Button cmdCancel {
			get { return withEventsField_cmdCancel; }
			set {
				if (withEventsField_cmdCancel != null) {
					withEventsField_cmdCancel.Click -= cmdCancel_Click;
				}
				withEventsField_cmdCancel = value;
				if (withEventsField_cmdCancel != null) {
					withEventsField_cmdCancel.Click += cmdCancel_Click;
				}
			}
		}
		private System.Windows.Forms.Button withEventsField_cmdUpdate;
		public System.Windows.Forms.Button cmdUpdate {
			get { return withEventsField_cmdUpdate; }
			set {
				if (withEventsField_cmdUpdate != null) {
					withEventsField_cmdUpdate.Click -= cmdUpdate_Click;
				}
				withEventsField_cmdUpdate = value;
				if (withEventsField_cmdUpdate != null) {
					withEventsField_cmdUpdate.Click += cmdUpdate_Click;
				}
			}
		}
		public System.Windows.Forms.TextBox txtLastupdateDate;
		public System.Windows.Forms.TextBox txtIndicatorDescription;
		public System.Windows.Forms.Label Label26;
		public System.Windows.Forms.Label Label23;
		public System.Windows.Forms.Label Label22;
		public System.Windows.Forms.Label Label21;
		public System.Windows.Forms.Label Label20;
		public System.Windows.Forms.Label Label19;
		public System.Windows.Forms.Label Label17;
		public System.Windows.Forms.Label Label14;
		public System.Windows.Forms.Label Label18;
		public System.Windows.Forms.Label Label16;
		public System.Windows.Forms.Label Label11;
		public System.Windows.Forms.Label Label10;
		public System.Windows.Forms.Label Label9;
		public System.Windows.Forms.Label Label8;
		public System.Windows.Forms.Label Label7;
		public System.Windows.Forms.Label Label6;
		public System.Windows.Forms.Label Label5;
		public System.Windows.Forms.Label Label4;
		public System.Windows.Forms.Label Label3;
		public System.Windows.Forms.Label Label2;
		public System.Windows.Forms.Label Label1;
//NOTE: The following procedure is required by the Windows Form Designer
//It can be modified using the Windows Form Designer.
//Do not modify it using the code editor.
		[System.Diagnostics.DebuggerStepThrough()]
		private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(OldfrmIndicatorEdit));
			this.components = new System.ComponentModel.Container();
			this.ToolTip1 = new System.Windows.Forms.ToolTip(components);
			this.chkAppCare = new System.Windows.Forms.CheckBox();
			this.Frame2 = new System.Windows.Forms.GroupBox();
			this.lstICD = new System.Windows.Forms.ListBox();
			this.cboPatientType = new System.Windows.Forms.ComboBox();
			this.lstTotalCases = new System.Windows.Forms.ListBox();
			this.cboCMSSampleField = new System.Windows.Forms.ComboBox();
			this.cboMeasureDataUsage = new System.Windows.Forms.ComboBox();
			this.cboBaseType = new System.Windows.Forms.ComboBox();
			this.txtCMSCode = new System.Windows.Forms.TextBox();
			this.txtJCCode = new System.Windows.Forms.TextBox();
			this.cboRiskAdjustSGID = new System.Windows.Forms.ComboBox();
			this.cboContinuousSGID = new System.Windows.Forms.ComboBox();
			this.Frame1 = new System.Windows.Forms.GroupBox();
			this.cboEndDateTime = new System.Windows.Forms.ComboBox();
			this.cboStartDateTime = new System.Windows.Forms.ComboBox();
			this.cboStartDateDDID = new System.Windows.Forms.ComboBox();
			this.cboEndDateDDID = new System.Windows.Forms.ComboBox();
			this.cboStartTimeDDID = new System.Windows.Forms.ComboBox();
			this.cboEndTimeDDID = new System.Windows.Forms.ComboBox();
			this.Label25 = new System.Windows.Forms.Label();
			this.Label24 = new System.Windows.Forms.Label();
			this.Label15 = new System.Windows.Forms.Label();
			this.txtStartTime = new System.Windows.Forms.Label();
			this.Label13 = new System.Windows.Forms.Label();
			this.Label12 = new System.Windows.Forms.Label();
			this.cboSPageOrientation = new System.Windows.Forms.ComboBox();
			this.txtScale = new System.Windows.Forms.TextBox();
			this.cboBreakoutType = new System.Windows.Forms.ComboBox();
			this.cboBestPractice = new System.Windows.Forms.ComboBox();
			this.cboMeasureTimeUnit = new System.Windows.Forms.ComboBox();
			this.cboRiskAdjusted = new System.Windows.Forms.ComboBox();
			this.cboCalcType = new System.Windows.Forms.ComboBox();
			this.cboIndicatorType = new System.Windows.Forms.ComboBox();
			this.txtJCAHOID = new System.Windows.Forms.TextBox();
			this.cmdCancel = new System.Windows.Forms.Button();
			this.cmdUpdate = new System.Windows.Forms.Button();
			this.txtLastupdateDate = new System.Windows.Forms.TextBox();
			this.txtIndicatorDescription = new System.Windows.Forms.TextBox();
			this.Label26 = new System.Windows.Forms.Label();
			this.Label23 = new System.Windows.Forms.Label();
			this.Label22 = new System.Windows.Forms.Label();
			this.Label21 = new System.Windows.Forms.Label();
			this.Label20 = new System.Windows.Forms.Label();
			this.Label19 = new System.Windows.Forms.Label();
			this.Label17 = new System.Windows.Forms.Label();
			this.Label14 = new System.Windows.Forms.Label();
			this.Label18 = new System.Windows.Forms.Label();
			this.Label16 = new System.Windows.Forms.Label();
			this.Label11 = new System.Windows.Forms.Label();
			this.Label10 = new System.Windows.Forms.Label();
			this.Label9 = new System.Windows.Forms.Label();
			this.Label8 = new System.Windows.Forms.Label();
			this.Label7 = new System.Windows.Forms.Label();
			this.Label6 = new System.Windows.Forms.Label();
			this.Label5 = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.Label3 = new System.Windows.Forms.Label();
			this.Label2 = new System.Windows.Forms.Label();
			this.Label1 = new System.Windows.Forms.Label();
			this.Frame2.SuspendLayout();
			this.Frame1.SuspendLayout();
			this.SuspendLayout();
			this.ToolTip1.Active = true;
			this.Text = "Update Indicator";
			this.ClientSize = new System.Drawing.Size(1223, 807);
			this.Location = new System.Drawing.Point(5, 29);
			this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultLocation;
			this.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.Control;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
			this.ControlBox = true;
			this.Enabled = true;
			this.KeyPreview = false;
			this.MaximizeBox = true;
			this.MinimizeBox = true;
			this.Cursor = System.Windows.Forms.Cursors.Default;
			this.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.ShowInTaskbar = true;
			this.HelpButton = false;
			this.WindowState = System.Windows.Forms.FormWindowState.Normal;
			this.Name = "frmIndicatorEdit";
			this.chkAppCare.Text = "Appropriate Care Measure Indicator";
			this.chkAppCare.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.chkAppCare.Size = new System.Drawing.Size(392, 22);
			this.chkAppCare.Location = new System.Drawing.Point(750, 100);
			this.chkAppCare.TabIndex = 58;
			this.chkAppCare.CheckAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.chkAppCare.FlatStyle = System.Windows.Forms.FlatStyle.Standard;
			this.chkAppCare.BackColor = System.Drawing.SystemColors.Control;
			this.chkAppCare.CausesValidation = true;
			this.chkAppCare.Enabled = true;
			this.chkAppCare.ForeColor = System.Drawing.SystemColors.ControlText;
			this.chkAppCare.Cursor = System.Windows.Forms.Cursors.Default;
			this.chkAppCare.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.chkAppCare.Appearance = System.Windows.Forms.Appearance.Normal;
			this.chkAppCare.TabStop = true;
			this.chkAppCare.CheckState = System.Windows.Forms.CheckState.Unchecked;
			this.chkAppCare.Visible = true;
			this.chkAppCare.Name = "chkAppCare";
			this.Frame2.Text = "ICD Population";
			this.Frame2.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Frame2.Size = new System.Drawing.Size(702, 152);
			this.Frame2.Location = new System.Drawing.Point(10, 590);
			this.Frame2.TabIndex = 56;
			this.Frame2.BackColor = System.Drawing.SystemColors.Control;
			this.Frame2.Enabled = true;
			this.Frame2.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Frame2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Frame2.Visible = true;
			this.Frame2.Padding = new System.Windows.Forms.Padding(0);
			this.Frame2.Name = "Frame2";
			this.lstICD.Size = new System.Drawing.Size(682, 107);
			this.lstICD.Location = new System.Drawing.Point(10, 30);
			this.lstICD.SelectionMode = System.Windows.Forms.SelectionMode.MultiExtended;
			this.lstICD.TabIndex = 57;
			this.lstICD.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.lstICD.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.lstICD.BackColor = System.Drawing.SystemColors.Window;
			this.lstICD.CausesValidation = true;
			this.lstICD.Enabled = true;
			this.lstICD.ForeColor = System.Drawing.SystemColors.WindowText;
			this.lstICD.IntegralHeight = true;
			this.lstICD.Cursor = System.Windows.Forms.Cursors.Default;
			this.lstICD.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.lstICD.Sorted = false;
			this.lstICD.TabStop = true;
			this.lstICD.Visible = true;
			this.lstICD.MultiColumn = false;
			this.lstICD.Name = "lstICD";
			this.cboPatientType.Size = new System.Drawing.Size(262, 27);
			this.cboPatientType.Location = new System.Drawing.Point(900, 50);
			this.cboPatientType.TabIndex = 45;
			this.cboPatientType.Text = "Combo1";
			this.cboPatientType.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboPatientType.BackColor = System.Drawing.SystemColors.Window;
			this.cboPatientType.CausesValidation = true;
			this.cboPatientType.Enabled = true;
			this.cboPatientType.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboPatientType.IntegralHeight = true;
			this.cboPatientType.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboPatientType.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboPatientType.Sorted = false;
			this.cboPatientType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboPatientType.TabStop = true;
			this.cboPatientType.Visible = true;
			this.cboPatientType.Name = "cboPatientType";
			this.lstTotalCases.Size = new System.Drawing.Size(462, 107);
			this.lstTotalCases.Location = new System.Drawing.Point(730, 450);
			this.lstTotalCases.SelectionMode = System.Windows.Forms.SelectionMode.MultiExtended;
			this.lstTotalCases.TabIndex = 44;
			this.lstTotalCases.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.lstTotalCases.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.lstTotalCases.BackColor = System.Drawing.SystemColors.Window;
			this.lstTotalCases.CausesValidation = true;
			this.lstTotalCases.Enabled = true;
			this.lstTotalCases.ForeColor = System.Drawing.SystemColors.WindowText;
			this.lstTotalCases.IntegralHeight = true;
			this.lstTotalCases.Cursor = System.Windows.Forms.Cursors.Default;
			this.lstTotalCases.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.lstTotalCases.Sorted = false;
			this.lstTotalCases.TabStop = true;
			this.lstTotalCases.Visible = true;
			this.lstTotalCases.MultiColumn = false;
			this.lstTotalCases.Name = "lstTotalCases";
			this.cboCMSSampleField.Size = new System.Drawing.Size(472, 27);
			this.cboCMSSampleField.Location = new System.Drawing.Point(230, 530);
			this.cboCMSSampleField.TabIndex = 41;
			this.cboCMSSampleField.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboCMSSampleField.BackColor = System.Drawing.SystemColors.Window;
			this.cboCMSSampleField.CausesValidation = true;
			this.cboCMSSampleField.Enabled = true;
			this.cboCMSSampleField.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboCMSSampleField.IntegralHeight = true;
			this.cboCMSSampleField.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboCMSSampleField.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboCMSSampleField.Sorted = false;
			this.cboCMSSampleField.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboCMSSampleField.TabStop = true;
			this.cboCMSSampleField.Visible = true;
			this.cboCMSSampleField.Name = "cboCMSSampleField";
			this.cboMeasureDataUsage.Size = new System.Drawing.Size(183, 27);
			this.cboMeasureDataUsage.Location = new System.Drawing.Point(543, 168);
			this.cboMeasureDataUsage.TabIndex = 40;
			this.cboMeasureDataUsage.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboMeasureDataUsage.BackColor = System.Drawing.SystemColors.Window;
			this.cboMeasureDataUsage.CausesValidation = true;
			this.cboMeasureDataUsage.Enabled = true;
			this.cboMeasureDataUsage.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboMeasureDataUsage.IntegralHeight = true;
			this.cboMeasureDataUsage.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboMeasureDataUsage.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboMeasureDataUsage.Sorted = false;
			this.cboMeasureDataUsage.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboMeasureDataUsage.TabStop = true;
			this.cboMeasureDataUsage.Visible = true;
			this.cboMeasureDataUsage.Name = "cboMeasureDataUsage";
			this.cboBaseType.Size = new System.Drawing.Size(184, 27);
			this.cboBaseType.Location = new System.Drawing.Point(164, 195);
			this.cboBaseType.TabIndex = 39;
			this.cboBaseType.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboBaseType.BackColor = System.Drawing.SystemColors.Window;
			this.cboBaseType.CausesValidation = true;
			this.cboBaseType.Enabled = true;
			this.cboBaseType.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboBaseType.IntegralHeight = true;
			this.cboBaseType.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboBaseType.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboBaseType.Sorted = false;
			this.cboBaseType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboBaseType.TabStop = true;
			this.cboBaseType.Visible = true;
			this.cboBaseType.Name = "cboBaseType";
			this.txtCMSCode.AutoSize = false;
			this.txtCMSCode.Size = new System.Drawing.Size(112, 24);
			this.txtCMSCode.Location = new System.Drawing.Point(543, 53);
			this.txtCMSCode.TabIndex = 35;
			this.txtCMSCode.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtCMSCode.AcceptsReturn = true;
			this.txtCMSCode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtCMSCode.BackColor = System.Drawing.SystemColors.Window;
			this.txtCMSCode.CausesValidation = true;
			this.txtCMSCode.Enabled = true;
			this.txtCMSCode.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtCMSCode.HideSelection = true;
			this.txtCMSCode.ReadOnly = false;
			this.txtCMSCode.MaxLength = 0;
			this.txtCMSCode.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtCMSCode.Multiline = false;
			this.txtCMSCode.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtCMSCode.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtCMSCode.TabStop = true;
			this.txtCMSCode.Visible = true;
			this.txtCMSCode.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtCMSCode.Name = "txtCMSCode";
			this.txtJCCode.AutoSize = false;
			this.txtJCCode.Size = new System.Drawing.Size(114, 24);
			this.txtJCCode.Location = new System.Drawing.Point(164, 53);
			this.txtJCCode.TabIndex = 33;
			this.txtJCCode.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtJCCode.AcceptsReturn = true;
			this.txtJCCode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtJCCode.BackColor = System.Drawing.SystemColors.Window;
			this.txtJCCode.CausesValidation = true;
			this.txtJCCode.Enabled = true;
			this.txtJCCode.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtJCCode.HideSelection = true;
			this.txtJCCode.ReadOnly = false;
			this.txtJCCode.MaxLength = 0;
			this.txtJCCode.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtJCCode.Multiline = false;
			this.txtJCCode.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtJCCode.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtJCCode.TabStop = true;
			this.txtJCCode.Visible = true;
			this.txtJCCode.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtJCCode.Name = "txtJCCode";
			this.cboRiskAdjustSGID.Size = new System.Drawing.Size(472, 27);
			this.cboRiskAdjustSGID.Location = new System.Drawing.Point(230, 490);
			this.cboRiskAdjustSGID.TabIndex = 32;
			this.cboRiskAdjustSGID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboRiskAdjustSGID.BackColor = System.Drawing.SystemColors.Window;
			this.cboRiskAdjustSGID.CausesValidation = true;
			this.cboRiskAdjustSGID.Enabled = true;
			this.cboRiskAdjustSGID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboRiskAdjustSGID.IntegralHeight = true;
			this.cboRiskAdjustSGID.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboRiskAdjustSGID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboRiskAdjustSGID.Sorted = false;
			this.cboRiskAdjustSGID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboRiskAdjustSGID.TabStop = true;
			this.cboRiskAdjustSGID.Visible = true;
			this.cboRiskAdjustSGID.Name = "cboRiskAdjustSGID";
			this.cboContinuousSGID.Size = new System.Drawing.Size(472, 27);
			this.cboContinuousSGID.Location = new System.Drawing.Point(230, 450);
			this.cboContinuousSGID.TabIndex = 29;
			this.cboContinuousSGID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboContinuousSGID.BackColor = System.Drawing.SystemColors.Window;
			this.cboContinuousSGID.CausesValidation = true;
			this.cboContinuousSGID.Enabled = true;
			this.cboContinuousSGID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboContinuousSGID.IntegralHeight = true;
			this.cboContinuousSGID.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboContinuousSGID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboContinuousSGID.Sorted = false;
			this.cboContinuousSGID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboContinuousSGID.TabStop = true;
			this.cboContinuousSGID.Visible = true;
			this.cboContinuousSGID.Name = "cboContinuousSGID";
			this.Frame1.Text = "Time Related Fields";
			this.Frame1.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Frame1.ForeColor = System.Drawing.Color.Blue;
			this.Frame1.Size = new System.Drawing.Size(1180, 152);
			this.Frame1.Location = new System.Drawing.Point(37, 269);
			this.Frame1.TabIndex = 24;
			this.Frame1.BackColor = System.Drawing.SystemColors.Control;
			this.Frame1.Enabled = true;
			this.Frame1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Frame1.Visible = true;
			this.Frame1.Padding = new System.Windows.Forms.Padding(0);
			this.Frame1.Name = "Frame1";
			this.cboEndDateTime.Size = new System.Drawing.Size(374, 27);
			this.cboEndDateTime.Location = new System.Drawing.Point(787, 90);
			this.cboEndDateTime.TabIndex = 54;
			this.cboEndDateTime.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboEndDateTime.BackColor = System.Drawing.SystemColors.Window;
			this.cboEndDateTime.CausesValidation = true;
			this.cboEndDateTime.Enabled = true;
			this.cboEndDateTime.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboEndDateTime.IntegralHeight = true;
			this.cboEndDateTime.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboEndDateTime.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboEndDateTime.Sorted = false;
			this.cboEndDateTime.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboEndDateTime.TabStop = true;
			this.cboEndDateTime.Visible = true;
			this.cboEndDateTime.Name = "cboEndDateTime";
			this.cboStartDateTime.Size = new System.Drawing.Size(374, 27);
			this.cboStartDateTime.Location = new System.Drawing.Point(790, 30);
			this.cboStartDateTime.TabIndex = 51;
			this.cboStartDateTime.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboStartDateTime.BackColor = System.Drawing.SystemColors.Window;
			this.cboStartDateTime.CausesValidation = true;
			this.cboStartDateTime.Enabled = true;
			this.cboStartDateTime.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboStartDateTime.IntegralHeight = true;
			this.cboStartDateTime.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboStartDateTime.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboStartDateTime.Sorted = false;
			this.cboStartDateTime.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboStartDateTime.TabStop = true;
			this.cboStartDateTime.Visible = true;
			this.cboStartDateTime.Name = "cboStartDateTime";
			this.cboStartDateDDID.Size = new System.Drawing.Size(374, 27);
			this.cboStartDateDDID.Location = new System.Drawing.Point(148, 27);
			this.cboStartDateDDID.TabIndex = 50;
			this.cboStartDateDDID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboStartDateDDID.BackColor = System.Drawing.SystemColors.Window;
			this.cboStartDateDDID.CausesValidation = true;
			this.cboStartDateDDID.Enabled = true;
			this.cboStartDateDDID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboStartDateDDID.IntegralHeight = true;
			this.cboStartDateDDID.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboStartDateDDID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboStartDateDDID.Sorted = false;
			this.cboStartDateDDID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboStartDateDDID.TabStop = true;
			this.cboStartDateDDID.Visible = true;
			this.cboStartDateDDID.Name = "cboStartDateDDID";
			this.cboEndDateDDID.Size = new System.Drawing.Size(374, 27);
			this.cboEndDateDDID.Location = new System.Drawing.Point(147, 89);
			this.cboEndDateDDID.TabIndex = 49;
			this.cboEndDateDDID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboEndDateDDID.BackColor = System.Drawing.SystemColors.Window;
			this.cboEndDateDDID.CausesValidation = true;
			this.cboEndDateDDID.Enabled = true;
			this.cboEndDateDDID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboEndDateDDID.IntegralHeight = true;
			this.cboEndDateDDID.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboEndDateDDID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboEndDateDDID.Sorted = false;
			this.cboEndDateDDID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboEndDateDDID.TabStop = true;
			this.cboEndDateDDID.Visible = true;
			this.cboEndDateDDID.Name = "cboEndDateDDID";
			this.cboStartTimeDDID.Size = new System.Drawing.Size(374, 27);
			this.cboStartTimeDDID.Location = new System.Drawing.Point(148, 55);
			this.cboStartTimeDDID.TabIndex = 48;
			this.cboStartTimeDDID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboStartTimeDDID.BackColor = System.Drawing.SystemColors.Window;
			this.cboStartTimeDDID.CausesValidation = true;
			this.cboStartTimeDDID.Enabled = true;
			this.cboStartTimeDDID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboStartTimeDDID.IntegralHeight = true;
			this.cboStartTimeDDID.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboStartTimeDDID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboStartTimeDDID.Sorted = false;
			this.cboStartTimeDDID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboStartTimeDDID.TabStop = true;
			this.cboStartTimeDDID.Visible = true;
			this.cboStartTimeDDID.Name = "cboStartTimeDDID";
			this.cboEndTimeDDID.Size = new System.Drawing.Size(374, 27);
			this.cboEndTimeDDID.Location = new System.Drawing.Point(147, 118);
			this.cboEndTimeDDID.TabIndex = 47;
			this.cboEndTimeDDID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboEndTimeDDID.BackColor = System.Drawing.SystemColors.Window;
			this.cboEndTimeDDID.CausesValidation = true;
			this.cboEndTimeDDID.Enabled = true;
			this.cboEndTimeDDID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboEndTimeDDID.IntegralHeight = true;
			this.cboEndTimeDDID.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboEndTimeDDID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboEndTimeDDID.Sorted = false;
			this.cboEndTimeDDID.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboEndTimeDDID.TabStop = true;
			this.cboEndTimeDDID.Visible = true;
			this.cboEndTimeDDID.Name = "cboEndTimeDDID";
			this.Label25.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label25.Text = "End Date/Time Field";
			this.Label25.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label25.Size = new System.Drawing.Size(162, 23);
			this.Label25.Location = new System.Drawing.Point(620, 90);
			this.Label25.TabIndex = 53;
			this.Label25.BackColor = System.Drawing.SystemColors.Control;
			this.Label25.Enabled = true;
			this.Label25.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label25.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label25.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label25.UseMnemonic = true;
			this.Label25.Visible = true;
			this.Label25.AutoSize = false;
			this.Label25.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label25.Name = "Label25";
			this.Label24.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label24.Text = "Start Date/Time Field";
			this.Label24.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label24.Size = new System.Drawing.Size(172, 23);
			this.Label24.Location = new System.Drawing.Point(610, 30);
			this.Label24.TabIndex = 52;
			this.Label24.BackColor = System.Drawing.SystemColors.Control;
			this.Label24.Enabled = true;
			this.Label24.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label24.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label24.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label24.UseMnemonic = true;
			this.Label24.Visible = true;
			this.Label24.AutoSize = false;
			this.Label24.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label24.Name = "Label24";
			this.Label15.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label15.Text = "End Time Field";
			this.Label15.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label15.Size = new System.Drawing.Size(122, 23);
			this.Label15.Location = new System.Drawing.Point(20, 118);
			this.Label15.TabIndex = 28;
			this.Label15.BackColor = System.Drawing.SystemColors.Control;
			this.Label15.Enabled = true;
			this.Label15.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label15.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label15.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label15.UseMnemonic = true;
			this.Label15.Visible = true;
			this.Label15.AutoSize = false;
			this.Label15.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label15.Name = "Label15";
			this.txtStartTime.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.txtStartTime.Text = "Start Time Field";
			this.txtStartTime.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtStartTime.Size = new System.Drawing.Size(122, 23);
			this.txtStartTime.Location = new System.Drawing.Point(22, 55);
			this.txtStartTime.TabIndex = 27;
			this.txtStartTime.BackColor = System.Drawing.SystemColors.Control;
			this.txtStartTime.Enabled = true;
			this.txtStartTime.ForeColor = System.Drawing.SystemColors.ControlText;
			this.txtStartTime.Cursor = System.Windows.Forms.Cursors.Default;
			this.txtStartTime.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtStartTime.UseMnemonic = true;
			this.txtStartTime.Visible = true;
			this.txtStartTime.AutoSize = false;
			this.txtStartTime.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.txtStartTime.Name = "txtStartTime";
			this.Label13.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label13.Text = "End Date Field";
			this.Label13.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label13.Size = new System.Drawing.Size(122, 23);
			this.Label13.Location = new System.Drawing.Point(20, 89);
			this.Label13.TabIndex = 26;
			this.Label13.BackColor = System.Drawing.SystemColors.Control;
			this.Label13.Enabled = true;
			this.Label13.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label13.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label13.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label13.UseMnemonic = true;
			this.Label13.Visible = true;
			this.Label13.AutoSize = false;
			this.Label13.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label13.Name = "Label13";
			this.Label12.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label12.Text = "Start Date Field";
			this.Label12.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label12.Size = new System.Drawing.Size(122, 23);
			this.Label12.Location = new System.Drawing.Point(23, 27);
			this.Label12.TabIndex = 25;
			this.Label12.BackColor = System.Drawing.SystemColors.Control;
			this.Label12.Enabled = true;
			this.Label12.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label12.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label12.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label12.UseMnemonic = true;
			this.Label12.Visible = true;
			this.Label12.AutoSize = false;
			this.Label12.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label12.Name = "Label12";
			this.cboSPageOrientation.Size = new System.Drawing.Size(99, 27);
			this.cboSPageOrientation.Location = new System.Drawing.Point(543, 227);
			this.cboSPageOrientation.TabIndex = 22;
			this.cboSPageOrientation.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboSPageOrientation.BackColor = System.Drawing.SystemColors.Window;
			this.cboSPageOrientation.CausesValidation = true;
			this.cboSPageOrientation.Enabled = true;
			this.cboSPageOrientation.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboSPageOrientation.IntegralHeight = true;
			this.cboSPageOrientation.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboSPageOrientation.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboSPageOrientation.Sorted = false;
			this.cboSPageOrientation.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboSPageOrientation.TabStop = true;
			this.cboSPageOrientation.Visible = true;
			this.cboSPageOrientation.Name = "cboSPageOrientation";
			this.txtScale.AutoSize = false;
			this.txtScale.Size = new System.Drawing.Size(80, 24);
			this.txtScale.Location = new System.Drawing.Point(543, 198);
			this.txtScale.TabIndex = 20;
			this.txtScale.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtScale.AcceptsReturn = true;
			this.txtScale.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtScale.BackColor = System.Drawing.SystemColors.Window;
			this.txtScale.CausesValidation = true;
			this.txtScale.Enabled = true;
			this.txtScale.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtScale.HideSelection = true;
			this.txtScale.ReadOnly = false;
			this.txtScale.MaxLength = 0;
			this.txtScale.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtScale.Multiline = false;
			this.txtScale.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtScale.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtScale.TabStop = true;
			this.txtScale.Visible = true;
			this.txtScale.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtScale.Name = "txtScale";
			this.cboBreakoutType.Size = new System.Drawing.Size(184, 27);
			this.cboBreakoutType.Location = new System.Drawing.Point(543, 139);
			this.cboBreakoutType.TabIndex = 18;
			this.cboBreakoutType.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboBreakoutType.BackColor = System.Drawing.SystemColors.Window;
			this.cboBreakoutType.CausesValidation = true;
			this.cboBreakoutType.Enabled = true;
			this.cboBreakoutType.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboBreakoutType.IntegralHeight = true;
			this.cboBreakoutType.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboBreakoutType.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboBreakoutType.Sorted = false;
			this.cboBreakoutType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboBreakoutType.TabStop = true;
			this.cboBreakoutType.Visible = true;
			this.cboBreakoutType.Name = "cboBreakoutType";
			this.cboBestPractice.Size = new System.Drawing.Size(99, 27);
			this.cboBestPractice.Location = new System.Drawing.Point(543, 109);
			this.cboBestPractice.TabIndex = 16;
			this.cboBestPractice.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboBestPractice.BackColor = System.Drawing.SystemColors.Window;
			this.cboBestPractice.CausesValidation = true;
			this.cboBestPractice.Enabled = true;
			this.cboBestPractice.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboBestPractice.IntegralHeight = true;
			this.cboBestPractice.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboBestPractice.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboBestPractice.Sorted = false;
			this.cboBestPractice.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboBestPractice.TabStop = true;
			this.cboBestPractice.Visible = true;
			this.cboBestPractice.Name = "cboBestPractice";
			this.cboMeasureTimeUnit.Size = new System.Drawing.Size(99, 27);
			this.cboMeasureTimeUnit.Location = new System.Drawing.Point(543, 79);
			this.cboMeasureTimeUnit.TabIndex = 14;
			this.cboMeasureTimeUnit.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboMeasureTimeUnit.BackColor = System.Drawing.SystemColors.Window;
			this.cboMeasureTimeUnit.CausesValidation = true;
			this.cboMeasureTimeUnit.Enabled = true;
			this.cboMeasureTimeUnit.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboMeasureTimeUnit.IntegralHeight = true;
			this.cboMeasureTimeUnit.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboMeasureTimeUnit.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboMeasureTimeUnit.Sorted = false;
			this.cboMeasureTimeUnit.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboMeasureTimeUnit.TabStop = true;
			this.cboMeasureTimeUnit.Visible = true;
			this.cboMeasureTimeUnit.Name = "cboMeasureTimeUnit";
			this.cboRiskAdjusted.Size = new System.Drawing.Size(99, 27);
			this.cboRiskAdjusted.Location = new System.Drawing.Point(164, 224);
			this.cboRiskAdjusted.TabIndex = 12;
			this.cboRiskAdjusted.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboRiskAdjusted.BackColor = System.Drawing.SystemColors.Window;
			this.cboRiskAdjusted.CausesValidation = true;
			this.cboRiskAdjusted.Enabled = true;
			this.cboRiskAdjusted.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboRiskAdjusted.IntegralHeight = true;
			this.cboRiskAdjusted.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboRiskAdjusted.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboRiskAdjusted.Sorted = false;
			this.cboRiskAdjusted.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboRiskAdjusted.TabStop = true;
			this.cboRiskAdjusted.Visible = true;
			this.cboRiskAdjusted.Name = "cboRiskAdjusted";
			this.cboCalcType.Size = new System.Drawing.Size(98, 27);
			this.cboCalcType.Location = new System.Drawing.Point(164, 167);
			this.cboCalcType.TabIndex = 10;
			this.cboCalcType.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboCalcType.BackColor = System.Drawing.SystemColors.Window;
			this.cboCalcType.CausesValidation = true;
			this.cboCalcType.Enabled = true;
			this.cboCalcType.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboCalcType.IntegralHeight = true;
			this.cboCalcType.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboCalcType.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboCalcType.Sorted = false;
			this.cboCalcType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboCalcType.TabStop = true;
			this.cboCalcType.Visible = true;
			this.cboCalcType.Name = "cboCalcType";
			this.cboIndicatorType.Size = new System.Drawing.Size(187, 27);
			this.cboIndicatorType.Location = new System.Drawing.Point(164, 135);
			this.cboIndicatorType.TabIndex = 8;
			this.cboIndicatorType.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cboIndicatorType.BackColor = System.Drawing.SystemColors.Window;
			this.cboIndicatorType.CausesValidation = true;
			this.cboIndicatorType.Enabled = true;
			this.cboIndicatorType.ForeColor = System.Drawing.SystemColors.WindowText;
			this.cboIndicatorType.IntegralHeight = true;
			this.cboIndicatorType.Cursor = System.Windows.Forms.Cursors.Default;
			this.cboIndicatorType.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cboIndicatorType.Sorted = false;
			this.cboIndicatorType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDown;
			this.cboIndicatorType.TabStop = true;
			this.cboIndicatorType.Visible = true;
			this.cboIndicatorType.Name = "cboIndicatorType";
			this.txtJCAHOID.AutoSize = false;
			this.txtJCAHOID.Size = new System.Drawing.Size(112, 24);
			this.txtJCAHOID.Location = new System.Drawing.Point(164, 79);
			this.txtJCAHOID.TabIndex = 6;
			this.txtJCAHOID.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtJCAHOID.AcceptsReturn = true;
			this.txtJCAHOID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtJCAHOID.BackColor = System.Drawing.SystemColors.Window;
			this.txtJCAHOID.CausesValidation = true;
			this.txtJCAHOID.Enabled = true;
			this.txtJCAHOID.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtJCAHOID.HideSelection = true;
			this.txtJCAHOID.ReadOnly = false;
			this.txtJCAHOID.MaxLength = 0;
			this.txtJCAHOID.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtJCAHOID.Multiline = false;
			this.txtJCAHOID.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtJCAHOID.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtJCAHOID.TabStop = true;
			this.txtJCAHOID.Visible = true;
			this.txtJCAHOID.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtJCAHOID.Name = "txtJCAHOID";
			this.cmdCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdCancel.Text = "Cancel";
			this.cmdCancel.Size = new System.Drawing.Size(125, 25);
			this.cmdCancel.Location = new System.Drawing.Point(650, 780);
			this.cmdCancel.TabIndex = 5;
			this.cmdCancel.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cmdCancel.BackColor = System.Drawing.SystemColors.Control;
			this.cmdCancel.CausesValidation = true;
			this.cmdCancel.Enabled = true;
			this.cmdCancel.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdCancel.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdCancel.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdCancel.TabStop = true;
			this.cmdCancel.Name = "cmdCancel";
			this.cmdUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmdUpdate.Text = "Update";
			this.cmdUpdate.Size = new System.Drawing.Size(125, 25);
			this.cmdUpdate.Location = new System.Drawing.Point(490, 780);
			this.cmdUpdate.TabIndex = 4;
			this.cmdUpdate.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.cmdUpdate.BackColor = System.Drawing.SystemColors.Control;
			this.cmdUpdate.CausesValidation = true;
			this.cmdUpdate.Enabled = true;
			this.cmdUpdate.ForeColor = System.Drawing.SystemColors.ControlText;
			this.cmdUpdate.Cursor = System.Windows.Forms.Cursors.Default;
			this.cmdUpdate.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.cmdUpdate.TabStop = true;
			this.cmdUpdate.Name = "cmdUpdate";
			this.txtLastupdateDate.AutoSize = false;
			this.txtLastupdateDate.Size = new System.Drawing.Size(112, 24);
			this.txtLastupdateDate.Location = new System.Drawing.Point(164, 108);
			this.txtLastupdateDate.TabIndex = 1;
			this.txtLastupdateDate.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtLastupdateDate.AcceptsReturn = true;
			this.txtLastupdateDate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtLastupdateDate.BackColor = System.Drawing.SystemColors.Window;
			this.txtLastupdateDate.CausesValidation = true;
			this.txtLastupdateDate.Enabled = true;
			this.txtLastupdateDate.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtLastupdateDate.HideSelection = true;
			this.txtLastupdateDate.ReadOnly = false;
			this.txtLastupdateDate.MaxLength = 0;
			this.txtLastupdateDate.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtLastupdateDate.Multiline = false;
			this.txtLastupdateDate.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtLastupdateDate.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtLastupdateDate.TabStop = true;
			this.txtLastupdateDate.Visible = true;
			this.txtLastupdateDate.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtLastupdateDate.Name = "txtLastupdateDate";
			this.txtIndicatorDescription.AutoSize = false;
			this.txtIndicatorDescription.Size = new System.Drawing.Size(598, 27);
			this.txtIndicatorDescription.Location = new System.Drawing.Point(129, 22);
			this.txtIndicatorDescription.TabIndex = 0;
			this.txtIndicatorDescription.Font = new System.Drawing.Font("Arial", 8f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.txtIndicatorDescription.AcceptsReturn = true;
			this.txtIndicatorDescription.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtIndicatorDescription.BackColor = System.Drawing.SystemColors.Window;
			this.txtIndicatorDescription.CausesValidation = true;
			this.txtIndicatorDescription.Enabled = true;
			this.txtIndicatorDescription.ForeColor = System.Drawing.SystemColors.WindowText;
			this.txtIndicatorDescription.HideSelection = true;
			this.txtIndicatorDescription.ReadOnly = false;
			this.txtIndicatorDescription.MaxLength = 0;
			this.txtIndicatorDescription.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtIndicatorDescription.Multiline = false;
			this.txtIndicatorDescription.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.txtIndicatorDescription.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtIndicatorDescription.TabStop = true;
			this.txtIndicatorDescription.Visible = true;
			this.txtIndicatorDescription.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.txtIndicatorDescription.Name = "txtIndicatorDescription";
			this.Label26.Text = "Total Cases";
			this.Label26.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label26.Size = new System.Drawing.Size(122, 22);
			this.Label26.Location = new System.Drawing.Point(730, 430);
			this.Label26.TabIndex = 55;
			this.Label26.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label26.BackColor = System.Drawing.SystemColors.Control;
			this.Label26.Enabled = true;
			this.Label26.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label26.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label26.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label26.UseMnemonic = true;
			this.Label26.Visible = true;
			this.Label26.AutoSize = false;
			this.Label26.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label26.Name = "Label26";
			this.Label23.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label23.Text = "Indicator Patient Type:";
			this.Label23.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label23.Size = new System.Drawing.Size(150, 38);
			this.Label23.Location = new System.Drawing.Point(750, 50);
			this.Label23.TabIndex = 46;
			this.Label23.BackColor = System.Drawing.SystemColors.Control;
			this.Label23.Enabled = true;
			this.Label23.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label23.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label23.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label23.UseMnemonic = true;
			this.Label23.Visible = true;
			this.Label23.AutoSize = false;
			this.Label23.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label23.Name = "Label23";
			this.Label22.Text = "Number of Cases (for Ratio Indicators)";
			this.Label22.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label22.Size = new System.Drawing.Size(382, 23);
			this.Label22.Location = new System.Drawing.Point(750, 400);
			this.Label22.TabIndex = 43;
			this.Label22.TextAlign = System.Drawing.ContentAlignment.TopLeft;
			this.Label22.BackColor = System.Drawing.SystemColors.Control;
			this.Label22.Enabled = true;
			this.Label22.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label22.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label22.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label22.UseMnemonic = true;
			this.Label22.Visible = true;
			this.Label22.AutoSize = false;
			this.Label22.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label22.Name = "Label22";
			this.Label21.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label21.Text = "CMS Sample Field";
			this.Label21.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label21.Size = new System.Drawing.Size(162, 23);
			this.Label21.Location = new System.Drawing.Point(60, 540);
			this.Label21.TabIndex = 42;
			this.Label21.BackColor = System.Drawing.SystemColors.Control;
			this.Label21.Enabled = true;
			this.Label21.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label21.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label21.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label21.UseMnemonic = true;
			this.Label21.Visible = true;
			this.Label21.AutoSize = false;
			this.Label21.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label21.Name = "Label21";
			this.Label20.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label20.Text = "Measure Data Usage:";
			this.Label20.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label20.Size = new System.Drawing.Size(173, 23);
			this.Label20.Location = new System.Drawing.Point(367, 172);
			this.Label20.TabIndex = 38;
			this.Label20.BackColor = System.Drawing.SystemColors.Control;
			this.Label20.Enabled = true;
			this.Label20.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label20.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label20.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label20.UseMnemonic = true;
			this.Label20.Visible = true;
			this.Label20.AutoSize = false;
			this.Label20.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label20.Name = "Label20";
			this.Label19.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label19.Text = "Base Type:";
			this.Label19.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label19.Size = new System.Drawing.Size(148, 22);
			this.Label19.Location = new System.Drawing.Point(8, 200);
			this.Label19.TabIndex = 37;
			this.Label19.BackColor = System.Drawing.SystemColors.Control;
			this.Label19.Enabled = true;
			this.Label19.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label19.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label19.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label19.UseMnemonic = true;
			this.Label19.Visible = true;
			this.Label19.AutoSize = false;
			this.Label19.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label19.Name = "Label19";
			this.Label17.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label17.Text = "CMS Code:";
			this.Label17.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label17.Size = new System.Drawing.Size(150, 18);
			this.Label17.Location = new System.Drawing.Point(388, 55);
			this.Label17.TabIndex = 36;
			this.Label17.BackColor = System.Drawing.SystemColors.Control;
			this.Label17.Enabled = true;
			this.Label17.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label17.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label17.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label17.UseMnemonic = true;
			this.Label17.Visible = true;
			this.Label17.AutoSize = false;
			this.Label17.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label17.Name = "Label17";
			this.Label14.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label14.Text = "JC Code:";
			this.Label14.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label14.Size = new System.Drawing.Size(150, 25);
			this.Label14.Location = new System.Drawing.Point(8, 57);
			this.Label14.TabIndex = 34;
			this.Label14.BackColor = System.Drawing.SystemColors.Control;
			this.Label14.Enabled = true;
			this.Label14.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label14.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label14.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label14.UseMnemonic = true;
			this.Label14.Visible = true;
			this.Label14.AutoSize = false;
			this.Label14.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label14.Name = "Label14";
			this.Label18.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label18.Text = "Risk Adjusted Summary Field:";
			this.Label18.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label18.Size = new System.Drawing.Size(232, 23);
			this.Label18.Location = new System.Drawing.Point(-10, 500);
			this.Label18.TabIndex = 31;
			this.Label18.BackColor = System.Drawing.SystemColors.Control;
			this.Label18.Enabled = true;
			this.Label18.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label18.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label18.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label18.UseMnemonic = true;
			this.Label18.Visible = true;
			this.Label18.AutoSize = false;
			this.Label18.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label18.Name = "Label18";
			this.Label16.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label16.Text = "Continuous Summary Field:";
			this.Label16.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label16.Size = new System.Drawing.Size(202, 23);
			this.Label16.Location = new System.Drawing.Point(20, 457);
			this.Label16.TabIndex = 30;
			this.Label16.BackColor = System.Drawing.SystemColors.Control;
			this.Label16.Enabled = true;
			this.Label16.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label16.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label16.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label16.UseMnemonic = true;
			this.Label16.Visible = true;
			this.Label16.AutoSize = false;
			this.Label16.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label16.Name = "Label16";
			this.Label11.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label11.Text = "Statewide Page Orientation:";
			this.Label11.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label11.Size = new System.Drawing.Size(214, 23);
			this.Label11.Location = new System.Drawing.Point(325, 227);
			this.Label11.TabIndex = 23;
			this.Label11.BackColor = System.Drawing.SystemColors.Control;
			this.Label11.Enabled = true;
			this.Label11.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label11.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label11.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label11.UseMnemonic = true;
			this.Label11.Visible = true;
			this.Label11.AutoSize = false;
			this.Label11.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label11.Name = "Label11";
			this.Label10.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label10.Text = "Scale:";
			this.Label10.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label10.Size = new System.Drawing.Size(150, 20);
			this.Label10.Location = new System.Drawing.Point(389, 199);
			this.Label10.TabIndex = 21;
			this.Label10.BackColor = System.Drawing.SystemColors.Control;
			this.Label10.Enabled = true;
			this.Label10.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label10.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label10.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label10.UseMnemonic = true;
			this.Label10.Visible = true;
			this.Label10.AutoSize = false;
			this.Label10.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label10.Name = "Label10";
			this.Label9.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label9.Text = "Breakout Type:";
			this.Label9.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label9.Size = new System.Drawing.Size(150, 25);
			this.Label9.Location = new System.Drawing.Point(389, 144);
			this.Label9.TabIndex = 19;
			this.Label9.BackColor = System.Drawing.SystemColors.Control;
			this.Label9.Enabled = true;
			this.Label9.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label9.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label9.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label9.UseMnemonic = true;
			this.Label9.Visible = true;
			this.Label9.AutoSize = false;
			this.Label9.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label9.Name = "Label9";
			this.Label8.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label8.Text = "Best Practice:";
			this.Label8.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label8.Size = new System.Drawing.Size(150, 25);
			this.Label8.Location = new System.Drawing.Point(389, 114);
			this.Label8.TabIndex = 17;
			this.Label8.BackColor = System.Drawing.SystemColors.Control;
			this.Label8.Enabled = true;
			this.Label8.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label8.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label8.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label8.UseMnemonic = true;
			this.Label8.Visible = true;
			this.Label8.AutoSize = false;
			this.Label8.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label8.Name = "Label8";
			this.Label7.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label7.Text = "Meaure Time Unit:";
			this.Label7.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label7.Size = new System.Drawing.Size(150, 25);
			this.Label7.Location = new System.Drawing.Point(389, 84);
			this.Label7.TabIndex = 15;
			this.Label7.BackColor = System.Drawing.SystemColors.Control;
			this.Label7.Enabled = true;
			this.Label7.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label7.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label7.UseMnemonic = true;
			this.Label7.Visible = true;
			this.Label7.AutoSize = false;
			this.Label7.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label7.Name = "Label7";
			this.Label6.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label6.Text = "Risk Adjusted?";
			this.Label6.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label6.Size = new System.Drawing.Size(150, 25);
			this.Label6.Location = new System.Drawing.Point(9, 228);
			this.Label6.TabIndex = 13;
			this.Label6.BackColor = System.Drawing.SystemColors.Control;
			this.Label6.Enabled = true;
			this.Label6.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label6.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label6.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label6.UseMnemonic = true;
			this.Label6.Visible = true;
			this.Label6.AutoSize = false;
			this.Label6.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label6.Name = "Label6";
			this.Label5.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label5.Text = "Calc. Type:";
			this.Label5.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label5.Size = new System.Drawing.Size(150, 25);
			this.Label5.Location = new System.Drawing.Point(9, 170);
			this.Label5.TabIndex = 11;
			this.Label5.BackColor = System.Drawing.SystemColors.Control;
			this.Label5.Enabled = true;
			this.Label5.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label5.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label5.UseMnemonic = true;
			this.Label5.Visible = true;
			this.Label5.AutoSize = false;
			this.Label5.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label5.Name = "Label5";
			this.Label4.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label4.Text = "Indicator Type:";
			this.Label4.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label4.Size = new System.Drawing.Size(150, 25);
			this.Label4.Location = new System.Drawing.Point(9, 140);
			this.Label4.TabIndex = 9;
			this.Label4.BackColor = System.Drawing.SystemColors.Control;
			this.Label4.Enabled = true;
			this.Label4.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label4.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label4.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label4.UseMnemonic = true;
			this.Label4.Visible = true;
			this.Label4.AutoSize = false;
			this.Label4.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label4.Name = "Label4";
			this.Label3.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label3.Text = "JCAHOID:";
			this.Label3.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label3.Size = new System.Drawing.Size(150, 25);
			this.Label3.Location = new System.Drawing.Point(9, 83);
			this.Label3.TabIndex = 7;
			this.Label3.BackColor = System.Drawing.SystemColors.Control;
			this.Label3.Enabled = true;
			this.Label3.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label3.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label3.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label3.UseMnemonic = true;
			this.Label3.Visible = true;
			this.Label3.AutoSize = false;
			this.Label3.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label3.Name = "Label3";
			this.Label2.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label2.Text = "Last Update Date:";
			this.Label2.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label2.Size = new System.Drawing.Size(150, 25);
			this.Label2.Location = new System.Drawing.Point(9, 109);
			this.Label2.TabIndex = 3;
			this.Label2.BackColor = System.Drawing.SystemColors.Control;
			this.Label2.Enabled = true;
			this.Label2.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label2.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label2.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label2.UseMnemonic = true;
			this.Label2.Visible = true;
			this.Label2.AutoSize = false;
			this.Label2.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label2.Name = "Label2";
			this.Label1.TextAlign = System.Drawing.ContentAlignment.TopRight;
			this.Label1.Text = "Indicator:";
			this.Label1.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, Convert.ToByte(0));
			this.Label1.Size = new System.Drawing.Size(84, 22);
			this.Label1.Location = new System.Drawing.Point(35, 22);
			this.Label1.TabIndex = 2;
			this.Label1.BackColor = System.Drawing.SystemColors.Control;
			this.Label1.Enabled = true;
			this.Label1.ForeColor = System.Drawing.SystemColors.ControlText;
			this.Label1.Cursor = System.Windows.Forms.Cursors.Default;
			this.Label1.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label1.UseMnemonic = true;
			this.Label1.Visible = true;
			this.Label1.AutoSize = false;
			this.Label1.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.Label1.Name = "Label1";
			this.Controls.Add(chkAppCare);
			this.Controls.Add(Frame2);
			this.Controls.Add(cboPatientType);
			this.Controls.Add(lstTotalCases);
			this.Controls.Add(cboCMSSampleField);
			this.Controls.Add(cboMeasureDataUsage);
			this.Controls.Add(cboBaseType);
			this.Controls.Add(txtCMSCode);
			this.Controls.Add(txtJCCode);
			this.Controls.Add(cboRiskAdjustSGID);
			this.Controls.Add(cboContinuousSGID);
			this.Controls.Add(Frame1);
			this.Controls.Add(cboSPageOrientation);
			this.Controls.Add(txtScale);
			this.Controls.Add(cboBreakoutType);
			this.Controls.Add(cboBestPractice);
			this.Controls.Add(cboMeasureTimeUnit);
			this.Controls.Add(cboRiskAdjusted);
			this.Controls.Add(cboCalcType);
			this.Controls.Add(cboIndicatorType);
			this.Controls.Add(txtJCAHOID);
			this.Controls.Add(cmdCancel);
			this.Controls.Add(cmdUpdate);
			this.Controls.Add(txtLastupdateDate);
			this.Controls.Add(txtIndicatorDescription);
			this.Controls.Add(Label26);
			this.Controls.Add(Label23);
			this.Controls.Add(Label22);
			this.Controls.Add(Label21);
			this.Controls.Add(Label20);
			this.Controls.Add(Label19);
			this.Controls.Add(Label17);
			this.Controls.Add(Label14);
			this.Controls.Add(Label18);
			this.Controls.Add(Label16);
			this.Controls.Add(Label11);
			this.Controls.Add(Label10);
			this.Controls.Add(Label9);
			this.Controls.Add(Label8);
			this.Controls.Add(Label7);
			this.Controls.Add(Label6);
			this.Controls.Add(Label5);
			this.Controls.Add(Label4);
			this.Controls.Add(Label3);
			this.Controls.Add(Label2);
			this.Controls.Add(Label1);
			this.Frame2.Controls.Add(lstICD);
			this.Frame1.Controls.Add(cboEndDateTime);
			this.Frame1.Controls.Add(cboStartDateTime);
			this.Frame1.Controls.Add(cboStartDateDDID);
			this.Frame1.Controls.Add(cboEndDateDDID);
			this.Frame1.Controls.Add(cboStartTimeDDID);
			this.Frame1.Controls.Add(cboEndTimeDDID);
			this.Frame1.Controls.Add(Label25);
			this.Frame1.Controls.Add(Label24);
			this.Frame1.Controls.Add(Label15);
			this.Frame1.Controls.Add(txtStartTime);
			this.Frame1.Controls.Add(Label13);
			this.Frame1.Controls.Add(Label12);
			this.Frame2.ResumeLayout(false);
			this.Frame1.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
	}
}
